package com.careershield.entity;

import com.careershield.enums.RiskLevel;
import com.careershield.enums.VerificationVerdict;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;

import java.util.ArrayList;
import java.util.List;

/**
 * Entity storing the comprehensive safety assessment generated by CareerShield AI.
 */
@Entity
@Table(name = "risk_assessments", indexes = {
    @Index(name = "idx_assessment_score", columnList = "overall_safety_score"),
    @Index(name = "idx_assessment_level", columnList = "risk_level")
})
public class RiskAssessment extends BaseEntity {

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "job_scan_id", nullable = false, unique = true)
    @JsonIgnore
    private JobScan jobScan;

    @Column(name = "overall_safety_score", nullable = false)
    private int overallSafetyScore; // 0 (Definite Scam) to 100 (Completely Safe)

    @Enumerated(EnumType.STRING)
    @Column(name = "risk_level", nullable = false, length = 20)
    private RiskLevel riskLevel;

    @Enumerated(EnumType.STRING)
    @Column(name = "verdict", nullable = false, length = 50)
    private VerificationVerdict verdict;

    @Column(name = "ml_confidence_score")
    private Double mlConfidenceScore; // 0.0 to 1.0

    @Column(name = "rule_engine_score")
    private Double ruleEngineScore;

    @Lob
    @Column(name = "summary_explanation", nullable = false, columnDefinition = "LONGTEXT")
    private String summaryExplanation;

    @Lob
    @Column(name = "safety_recommendation", nullable = false, columnDefinition = "LONGTEXT")
    private String safetyRecommendation;

    @OneToMany(mappedBy = "riskAssessment", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    private List<RiskFactor> riskFactors = new ArrayList<>();

    public RiskAssessment() {
    }

    public RiskAssessment(JobScan jobScan, int overallSafetyScore, RiskLevel riskLevel,
                          VerificationVerdict verdict, Double mlConfidenceScore,
                          Double ruleEngineScore, String summaryExplanation,
                          String safetyRecommendation) {
        this.jobScan = jobScan;
        this.overallSafetyScore = overallSafetyScore;
        this.riskLevel = riskLevel;
        this.verdict = verdict;
        this.mlConfidenceScore = mlConfidenceScore;
        this.ruleEngineScore = ruleEngineScore;
        this.summaryExplanation = summaryExplanation;
        this.safetyRecommendation = safetyRecommendation;
    }

    public void addRiskFactor(RiskFactor factor) {
        this.riskFactors.add(factor);
        factor.setRiskAssessment(this);
    }

    // Getters and Setters
    public JobScan getJobScan() {
        return jobScan;
    }

    public void setJobScan(JobScan jobScan) {
        this.jobScan = jobScan;
    }

    public int getOverallSafetyScore() {
        return overallSafetyScore;
    }

    public void setOverallSafetyScore(int overallSafetyScore) {
        this.overallSafetyScore = overallSafetyScore;
    }

    public RiskLevel getRiskLevel() {
        return riskLevel;
    }

    public void setRiskLevel(RiskLevel riskLevel) {
        this.riskLevel = riskLevel;
    }

    public VerificationVerdict getVerdict() {
        return verdict;
    }

    public void setVerdict(VerificationVerdict verdict) {
        this.verdict = verdict;
    }

    public Double getMlConfidenceScore() {
        return mlConfidenceScore;
    }

    public void setMlConfidenceScore(Double mlConfidenceScore) {
        this.mlConfidenceScore = mlConfidenceScore;
    }

    public Double getRuleEngineScore() {
        return ruleEngineScore;
    }

    public void setRuleEngineScore(Double ruleEngineScore) {
        this.ruleEngineScore = ruleEngineScore;
    }

    public String getSummaryExplanation() {
        return summaryExplanation;
    }

    public void setSummaryExplanation(String summaryExplanation) {
        this.summaryExplanation = summaryExplanation;
    }

    public String getSafetyRecommendation() {
        return safetyRecommendation;
    }

    public void setSafetyRecommendation(String safetyRecommendation) {
        this.safetyRecommendation = safetyRecommendation;
    }

    public List<RiskFactor> getRiskFactors() {
        return riskFactors;
    }

    public void setRiskFactors(List<RiskFactor> riskFactors) {
        this.riskFactors = riskFactors;
    }
}
